AB_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from directory.views import Register

urlpatterns = [
    path('register/success/', TemplateView.as_view(template_name="registration/success.html"), name='register-success'),
    path('register/', Register.as_view(), name='register'),
    path('map/', include(('directions.urls'), namespace='directions')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('directory.urls')),
]

directions/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
	path('', views.map, name="map"),
	]

directory/urls.py
from django.urls import include, path
from . import views
from .views import ContactList, ContactView, AddContactView, UpdateContactView, ContactDeleteView

urlpatterns = [
    path('', ContactList.as_view(), name='show-contacts'),
    path('add-contact/', AddContactView.as_view(), name='add-contact'),
    path('update_contact/<int:pk>', UpdateContactView.as_view(), name='update-contact'),
    path('delete_contact/<int:pk>', ContactDeleteView.as_view(), name='delete-contact'),
    path('contacts/<int:pk>', ContactView.as_view(), name='contact-detail'),
]

directions/models.py
from django.db import models

# Create your models here.

directory/models.py
from django.db import models
from django.contrib.auth.models import User
# from address.models import AddressField


class Contact(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(blank=True, null=True)
    birthday = models.DateField('Birthday', blank=True, null=True)
    notes = models.TextField('Notes', max_length=500, blank=True) 
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    address_line1 = models.CharField(max_length = 50, null=True, blank=True)
    address_line2 = models.CharField(max_length = 50, null=True, blank=True)
    address_ZIP = models.CharField(max_length = 5, null=True, blank=True)
    address_state = models.CharField(max_length = 50, null=True, blank=True)
    self_contact = models.BooleanField(default=False)
    

    def __str__(self):
        return (self.first_name + " " + self.last_name)

directory/forms.py
from django import forms
from .models import Contact
from crispy_forms.helper import FormHelper
from localflavor.us.forms import USZipCodeField, USStateSelect

class DateInput(forms.DateInput):
    input_type = 'date'


class ContactForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = Contact

        fields = (
            'first_name', 'last_name', 'email', 'birthday', 'notes', 'address_line1', 'address_line2', 'address_ZIP',
            'address_state',
        )
        # address_state = USStateSelect()
        address_state = forms.CharField(widget=USStateSelect)
        address_ZIP = USZipCodeField()

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'birthday': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'notes': forms.Textarea(attrs={'class': 'form-control'}),
            'address_line1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '123 Main St'}),
            'address_line2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apartment or Suite #'}),
        }

        labels = {
            'address_line1': 'Address 1',
            'address_line2': 'Address 2 (optional)',
            'address_ZIP': 'Zip code',
            'address_state': 'State',
        }

directions/views.py
from django.shortcuts import render
from django.conf import settings


def address_formatter(address):
	# cealns the addresses plassed in by URL to make it human-readable
	
	cleaned_address = address.split('-')
	while 'None' in cleaned_address:
		cleaned_address.remove('None')
	
	return ', '.join(cleaned_address)

'''
Basic view for displaying a map 
'''
def map(request):
	start_address = address_formatter(request.GET['start'])
	end_address = address_formatter(request.GET['end'])
	context = {"google_api_key": settings.GOOGLE_API_KEY, 'start': start_address, 'end': end_address}
	
	return render(request, 'directions/maps.html', context)

directory/views.py
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from datetime import timedelta, date
from django.db.models import Q

from .models import Contact
from .forms import ContactForm

class ContactList(LoginRequiredMixin, View):
    login_url = reverse_lazy('login')

    def get(self, request, *args, **kwargs):
        today = date.today()

        # people whose birthdays are coming up
        birthdays = Contact.objects.filter(username=self.request.user).filter(Q(birthday__month=today.month, birthday__day__gte=today.day) | Q(birthday__month=today.month+1)).filter(self_contact=False).order_by('-birthday__month').order_by('-birthday__day')[:5]
        all_contacts = Contact.objects.filter(username=self.request.user).order_by('last_name')
        return render(request, 'directory/contact_list.html', {'all_contacts':all_contacts, 'birthdays':birthdays})

class UpdateContactView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Contact
    context_object_name = 'contact'
    form_class = ContactForm
    template_name = 'directory/add_contact.html'

    def test_func(self):
        obj = self.get_object()
        return obj.username == self.request.user

    def form_valid(self, form):
        contact = form.save()  
        return redirect('contact-detail', pk=contact.pk)

class ContactView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Contact
    # context_object_name = 'contact'

    def test_func(self):
        obj = self.get_object()
        return obj.username == self.request.user

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['user_info'] = Contact.objects.filter(username=self.request.user).filter(self_contact=True).values()[0]
        return context

class AddContactView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'directory/add_contact.html'

    def form_valid(self, form):
        contact = form.save(commit=False)
        contact.username = self.request.user
        contact.save()  
        return redirect('contact-detail', pk=contact.pk)

class ContactDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Contact
    template_name = 'directory/delete_contact.html'
    context_object_name = 'contact'
    success_url = reverse_lazy('show-contacts')
    
    def test_func(self):
        obj = self.get_object()
        return obj.username == self.request.user

class Register(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register-success')

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.success_url)

AB_site/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="keywords" content="HTML,CSS,JavaScript">
        <meta name="author" content="John Fitzpatrick" />
        <title>Address Book</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Address Book</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" aria-current="page">Hello, {{ user.username }}</a></li>
                            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'logout' %}?next=/">Log Out</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'login' %}?next=/">Log in</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        
        <!-- Page content-->
        <div class="container">
            <div class="mt-5">
                {% block content %}
                    <h1>A Bootstrap 5 Starter Template</h1>
                    <p class="lead">A complete project boilerplate built with Bootstrap</p>
                    <p>Bootstrap v5.0.1</p>
                {% endblock content %}
            </div>
        </div>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        {% block extend_footer %}{% endblock %}
    </body>
</html>

AB_site/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bare - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h1>A Bootstrap 5 Starter Template</h1>
                <p class="lead">A complete project boilerplate built with Bootstrap</p>
                <p>Bootstrap v5.0.1</p>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

directions/templates/directions/maps.html
{% extends 'base.html' %}
{% load static %}


{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/maps.css' %}"></link>

{% endblock %}


{% block content %}

<h3>Directions</h3>
<div class="div-container">
  <div>
    <input
      id="origin-input"
      class="controls"
      type="text"
      placeholder="Enter an origin location"
      value="{{ start }}"
    />

    <input
      id="destination-input"
      class="controls"
      type="text"
      placeholder="Enter a destination location"
      value="{{ end }}"
    />

    <div id="mode-selector" class="controls">
      <input
        type="radio"
        name="type"
        id="changemode-walking"
        checked="checked"
      />
      <label for="changemode-walking">Walking</label>

      <input type="radio" name="type" id="changemode-transit" />
      <label for="changemode-transit">Transit</label>

      <input type="radio" name="type" id="changemode-driving" />
      <label for="changemode-driving">Driving</label>
    </div>
  </div>

  <div id="map"></div>

  <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key={{google_api_key|safe}}&callback=initMap&libraries=places&v=weekly"
    async
  ></script>
</div>

{% endblock %}


{% block extend_footer %}    
      <script src="{% static 'js/google_places.js' %}"></script>
{% endblock %}

directory/templates/directory/add_contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/contact.css' %}"></link>
{% endblock %}

{% block title %}Add Contact{% endblock title %}

{% block content %}
    <form method="post" class='form-inline' novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-5">
                {{ form.first_name|as_crispy_field }}
            </div>

            <div class="form-group col-5">
                {{ form.last_name|as_crispy_field }}
            </div>

            <div class="form-group col-2">
                {{ form.birthday|as_crispy_field }}
            </div>
        </div>

        <div class="row">
            <div class="form-group col-5">
                {{ form.address_line1|as_crispy_field }} 
            </div>
        </div>

        <div class="row">
            <div class="form-group col-5">
                {{ form.address_line2|as_crispy_field }} 
            </div>
        </div>
        
        <div class="row">
            <div class="form-group col-2">
                {{ form.address_ZIP|as_crispy_field }} 
            </div>
        
            <div class="form-group col-1">
                {{ form.address_state|as_crispy_field }} 
            </div>
        </div>

        </div>
        
        <div style="padding: 10px">
            {{ form.notes|as_crispy_field }}
        </div>

        <div>
            <!-- {{ form.address }} -->
        </div>
                
        <div style="padding: 10px">
            <button type="submit" class="btn btn-success">Save Contact</button>
        </div>
                  
    </form>

{% endblock content %}

directory/templates/directory/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Contact{% endblock title %}

{% block content %}
    {% if submitted %}
        <p class="success">
            Contact successfully added!
        </p>

    {% else %}
        <form method="post" novalidate>
            {% csrf_token %}
                <div class="row">
                  <div class="col-6">
                    {{ form.first_name|as_crispy_field }}
                  </div>
                  <div class="col-6">
                    {{ form.last_name|as_crispy_field }}
                  </div>
                </div>
                {{ form.email|as_crispy_field }}
                <!-- <label for="example-date-input" class="col-2 col-form-label">Date</label> -->
                <!-- {{ form.first_name.label }} -->
                {{ form.birthday|as_crispy_field }}
                {{ form.notes|as_crispy_field }}
            <button type="submit" class="btn btn-success">Save Contact</button>
        </form>
    
    {% endif %}


{% endblock content %}

directory/templates/directory/contact_detail.html
{% extends "base.html" %}
{% load static   %}

{% block extra_head %}
    <link href="{% static 'css/contact.css' %}" rel="stylesheet" />
{% endblock %}

{% block title %}Contact Detail{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-2">
            <a class="btn btn-primary" href="{% url 'show-contacts' %}" role="button">Home</a>
            <p></p>
            <a class="btn btn-secondary" href="{% url 'update-contact' contact.id %}" role="button">Edit Contact</a>
            <p></p>
            {% if not contact.self_contact %}
                <a class="btn btn-danger" href="{% url 'delete-contact' contact.id %}" role="button">Delete Contact</a>
            {% endif %}
            <p></p>
            {% if user_info.address_line1 != None and contact.address_line1 != None and not contact.self_contact %}
                <a class="btn btn-dark" href="{% url 'directions:map' %}?start={{ user_info.address_line1 }}-{{ user_info.address_ZIP }}-{{ user_info.address_state }}&end={{ contact.address_line1 }}-{{ contact.address_ZIP }}-{{ contact.address_state }}" role="button">Get Directions</a>
            {% endif %}
        </div>

        <div class="col-6">
            <h1>{{ contact.first_name }} {{ contact.last_name }}</h1>
            <h3>Basics</h3> 
            {% if contact.birthday %}<p><strong>Birthday &nbsp;&nbsp;&nbsp;&nbsp; </strong> {{ contact.birthday }}</p>{% endif %}

            <h3>Address</h3>
            
            {% if contact.address_line1 or contact.address_ZIP or contact.address_state %}
                {% if contact.address_line1 %}<p><strong>Address 1 &nbsp;&nbsp;&nbsp;&nbsp; </strong> {{ contact.address_line1 }}</p>{% endif %}
                
                {% if contact.address_line2 %}<p><strong>Address 2 &nbsp;&nbsp;&nbsp;&nbsp; </strong> {{ contact.address_line2 }}</p>{% endif %}
                
                {% if contact.address_ZIP %}<p><strong>Zip Code &nbsp;&nbsp;&nbsp;&nbsp; </strong> {{ contact.address_ZIP }}</p>{% endif %}
                
                {% if contact.address_state %}<p><strong>State &nbsp;&nbsp;&nbsp;&nbsp; </strong> {{ contact.address_state }}</p>{% endif %}
            
            {% else %}
                <p>No address information to display!</p>
            {% endif %}

            <h3>General Notes</h3>
                {{ contact.notes|linebreaks }}
        </div>

    </div>
    
{% endblock content %}

directory/templates/directory/contact_list.html
{% extends "base.html" %}
{% load static   %}

{% block extra_head %}
    <link href="{% static 'css/contact_list.css' %}" rel="stylesheet" />
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-2">
        <a class="btn btn-primary" href="{% url 'add-contact' %}" role="button">Add Contact</a>
    </div>

    <div class="col-6">
        {% for contact in all_contacts %}
            <div class="contactrow {% cycle '' 'altrow' %}">
                {% if contact.self_contact == False %}
                    <a href="{% url 'contact-detail' contact.id %}">{{ contact.first_name }} {{ contact.last_name }}</a>
                {% else %}
                    <a href="{% url 'contact-detail' contact.id %}">{{ contact.first_name }} {{ contact.last_name }} (My Profile)</a>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    <div class="col-2" id="birthday-div">
        <h2>Birthdays</h2>
            <ul>
                {% for birthday_person in birthdays %}
                    <li><a href="{% url 'contact-detail' birthday_person.id %}">{{ birthday_person.birthday|date:"F d" }}: {{ birthday_person.first_name }} {{ birthday_person.last_name }}</a></li>
                
                {% empty %}
                    <p>No upcoming birthdays</p>
                {% endfor %}
            </ul>
        </div> 
</div>

{% endblock content %}

directory/templates/directory/delete_contact.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete {{ contact.first_name }} {{ contact.last_name }} from your contacts?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}